// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64) && linux

package instrumentation

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type instrumentorGoFuncInfo struct {
	EntryPc uint64
	Pcsp    uint32
	Flag    uint8
	_       [3]byte
}

// loadInstrumentor returns the embedded CollectionSpec for instrumentor.
func loadInstrumentor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_InstrumentorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load instrumentor: %w", err)
	}

	return spec, err
}

// loadInstrumentorObjects loads instrumentor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*instrumentorObjects
//	*instrumentorPrograms
//	*instrumentorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadInstrumentorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadInstrumentor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// instrumentorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type instrumentorSpecs struct {
	instrumentorProgramSpecs
	instrumentorMapSpecs
	instrumentorVariableSpecs
}

// instrumentorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type instrumentorProgramSpecs struct {
	AvoidPreempt     *ebpf.ProgramSpec `ebpf:"avoid_preempt"`
	Delay            *ebpf.ProgramSpec `ebpf:"delay"`
	GoExecute        *ebpf.ProgramSpec `ebpf:"go_execute"`
	GoGlobrunqStatus *ebpf.ProgramSpec `ebpf:"go_globrunq_status"`
	GoGopark         *ebpf.ProgramSpec `ebpf:"go_gopark"`
	GoNewproc        *ebpf.ProgramSpec `ebpf:"go_newproc"`
	GoRunqStatus     *ebpf.ProgramSpec `ebpf:"go_runq_status"`
	GoSchedule       *ebpf.ProgramSpec `ebpf:"go_schedule"`
}

// instrumentorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type instrumentorMapSpecs struct {
	GoFunctab         *ebpf.MapSpec `ebpf:"go_functab"`
	InstrumentorEvent *ebpf.MapSpec `ebpf:"instrumentor_event"`
	SudogStacks       *ebpf.MapSpec `ebpf:"sudog_stacks"`
}

// instrumentorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type instrumentorVariableSpecs struct {
	EVENT_TYPE_DELAY           *ebpf.VariableSpec `ebpf:"EVENT_TYPE_DELAY"`
	EVENT_TYPE_FOUND_RUNNABLE  *ebpf.VariableSpec `ebpf:"EVENT_TYPE_FOUND_RUNNABLE"`
	EVENT_TYPE_GLOBRUNQ_STATUS *ebpf.VariableSpec `ebpf:"EVENT_TYPE_GLOBRUNQ_STATUS"`
	EVENT_TYPE_NEWPROC         *ebpf.VariableSpec `ebpf:"EVENT_TYPE_NEWPROC"`
	EVENT_TYPE_RUNQ_STATUS     *ebpf.VariableSpec `ebpf:"EVENT_TYPE_RUNQ_STATUS"`
	EVENT_TYPE_SCHEDULE        *ebpf.VariableSpec `ebpf:"EVENT_TYPE_SCHEDULE"`
	EVENT_TYPE_SEMTABLE_STATUS *ebpf.VariableSpec `ebpf:"EVENT_TYPE_SEMTABLE_STATUS"`
	AllpSliceAddr              *ebpf.VariableSpec `ebpf:"allp_slice_addr"`
	RuntimeSchedAddr           *ebpf.VariableSpec `ebpf:"runtime_sched_addr"`
	SemtabAddr                 *ebpf.VariableSpec `ebpf:"semtab_addr"`
	SemtabVersion              *ebpf.VariableSpec `ebpf:"semtab_version"`
}

// instrumentorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadInstrumentorObjects or ebpf.CollectionSpec.LoadAndAssign.
type instrumentorObjects struct {
	instrumentorPrograms
	instrumentorMaps
	instrumentorVariables
}

func (o *instrumentorObjects) Close() error {
	return _InstrumentorClose(
		&o.instrumentorPrograms,
		&o.instrumentorMaps,
	)
}

// instrumentorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadInstrumentorObjects or ebpf.CollectionSpec.LoadAndAssign.
type instrumentorMaps struct {
	GoFunctab         *ebpf.Map `ebpf:"go_functab"`
	InstrumentorEvent *ebpf.Map `ebpf:"instrumentor_event"`
	SudogStacks       *ebpf.Map `ebpf:"sudog_stacks"`
}

func (m *instrumentorMaps) Close() error {
	return _InstrumentorClose(
		m.GoFunctab,
		m.InstrumentorEvent,
		m.SudogStacks,
	)
}

// instrumentorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadInstrumentorObjects or ebpf.CollectionSpec.LoadAndAssign.
type instrumentorVariables struct {
	EVENT_TYPE_DELAY           *ebpf.Variable `ebpf:"EVENT_TYPE_DELAY"`
	EVENT_TYPE_FOUND_RUNNABLE  *ebpf.Variable `ebpf:"EVENT_TYPE_FOUND_RUNNABLE"`
	EVENT_TYPE_GLOBRUNQ_STATUS *ebpf.Variable `ebpf:"EVENT_TYPE_GLOBRUNQ_STATUS"`
	EVENT_TYPE_NEWPROC         *ebpf.Variable `ebpf:"EVENT_TYPE_NEWPROC"`
	EVENT_TYPE_RUNQ_STATUS     *ebpf.Variable `ebpf:"EVENT_TYPE_RUNQ_STATUS"`
	EVENT_TYPE_SCHEDULE        *ebpf.Variable `ebpf:"EVENT_TYPE_SCHEDULE"`
	EVENT_TYPE_SEMTABLE_STATUS *ebpf.Variable `ebpf:"EVENT_TYPE_SEMTABLE_STATUS"`
	AllpSliceAddr              *ebpf.Variable `ebpf:"allp_slice_addr"`
	RuntimeSchedAddr           *ebpf.Variable `ebpf:"runtime_sched_addr"`
	SemtabAddr                 *ebpf.Variable `ebpf:"semtab_addr"`
	SemtabVersion              *ebpf.Variable `ebpf:"semtab_version"`
}

// instrumentorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadInstrumentorObjects or ebpf.CollectionSpec.LoadAndAssign.
type instrumentorPrograms struct {
	AvoidPreempt     *ebpf.Program `ebpf:"avoid_preempt"`
	Delay            *ebpf.Program `ebpf:"delay"`
	GoExecute        *ebpf.Program `ebpf:"go_execute"`
	GoGlobrunqStatus *ebpf.Program `ebpf:"go_globrunq_status"`
	GoGopark         *ebpf.Program `ebpf:"go_gopark"`
	GoNewproc        *ebpf.Program `ebpf:"go_newproc"`
	GoRunqStatus     *ebpf.Program `ebpf:"go_runq_status"`
	GoSchedule       *ebpf.Program `ebpf:"go_schedule"`
}

func (p *instrumentorPrograms) Close() error {
	return _InstrumentorClose(
		p.AvoidPreempt,
		p.Delay,
		p.GoExecute,
		p.GoGlobrunqStatus,
		p.GoGopark,
		p.GoNewproc,
		p.GoRunqStatus,
		p.GoSchedule,
	)
}

func _InstrumentorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed instrumentor_bpfel.o
var _InstrumentorBytes []byte
