// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: exec.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=path,proto3,oneof" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ExecOneof:
	//
	//	*ExecResponse_RuntimeOutput
	//	*ExecResponse_RuntimeResult
	//	*ExecResponse_Gomaxprocs
	ExecOneof     isExecResponse_ExecOneof `protobuf_oneof:"exec_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetExecOneof() isExecResponse_ExecOneof {
	if x != nil {
		return x.ExecOneof
	}
	return nil
}

func (x *ExecResponse) GetRuntimeOutput() *RuntimeOutput {
	if x != nil {
		if x, ok := x.ExecOneof.(*ExecResponse_RuntimeOutput); ok {
			return x.RuntimeOutput
		}
	}
	return nil
}

func (x *ExecResponse) GetRuntimeResult() *RuntimeResult {
	if x != nil {
		if x, ok := x.ExecOneof.(*ExecResponse_RuntimeResult); ok {
			return x.RuntimeResult
		}
	}
	return nil
}

func (x *ExecResponse) GetGomaxprocs() int32 {
	if x != nil {
		if x, ok := x.ExecOneof.(*ExecResponse_Gomaxprocs); ok {
			return x.Gomaxprocs
		}
	}
	return 0
}

type isExecResponse_ExecOneof interface {
	isExecResponse_ExecOneof()
}

type ExecResponse_RuntimeOutput struct {
	RuntimeOutput *RuntimeOutput `protobuf:"bytes,1,opt,name=runtime_output,json=runtimeOutput,proto3,oneof"`
}

type ExecResponse_RuntimeResult struct {
	RuntimeResult *RuntimeResult `protobuf:"bytes,2,opt,name=runtime_result,json=runtimeResult,proto3,oneof"`
}

type ExecResponse_Gomaxprocs struct {
	Gomaxprocs int32 `protobuf:"varint,3,opt,name=gomaxprocs,proto3,oneof"`
}

func (*ExecResponse_RuntimeOutput) isExecResponse_ExecOneof() {}

func (*ExecResponse_RuntimeResult) isExecResponse_ExecOneof() {}

func (*ExecResponse_Gomaxprocs) isExecResponse_ExecOneof() {}

var File_exec_proto protoreflect.FileDescriptor

const file_exec_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"exec.proto\x12\n" +
	"slowmoexec\x1a\fslowmo.proto\"/\n" +
	"\vExecRequest\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x88\x01\x01B\a\n" +
	"\x05_path\"\xbe\x01\n" +
	"\fExecResponse\x12>\n" +
	"\x0eruntime_output\x18\x01 \x01(\v2\x15.slowmo.RuntimeOutputH\x00R\rruntimeOutput\x12>\n" +
	"\x0eruntime_result\x18\x02 \x01(\v2\x15.slowmo.RuntimeResultH\x00R\rruntimeResult\x12 \n" +
	"\n" +
	"gomaxprocs\x18\x03 \x01(\x05H\x00R\n" +
	"gomaxprocsB\f\n" +
	"\n" +
	"exec_oneof2J\n" +
	"\vExecService\x12;\n" +
	"\x04Exec\x12\x17.slowmoexec.ExecRequest\x1a\x18.slowmoexec.ExecResponse0\x01B$Z\"github.com/kailun2047/slowmo/protob\x06proto3"

var (
	file_exec_proto_rawDescOnce sync.Once
	file_exec_proto_rawDescData []byte
)

func file_exec_proto_rawDescGZIP() []byte {
	file_exec_proto_rawDescOnce.Do(func() {
		file_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)))
	})
	return file_exec_proto_rawDescData
}

var file_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exec_proto_goTypes = []any{
	(*ExecRequest)(nil),   // 0: slowmoexec.ExecRequest
	(*ExecResponse)(nil),  // 1: slowmoexec.ExecResponse
	(*RuntimeOutput)(nil), // 2: slowmo.RuntimeOutput
	(*RuntimeResult)(nil), // 3: slowmo.RuntimeResult
}
var file_exec_proto_depIdxs = []int32{
	2, // 0: slowmoexec.ExecResponse.runtime_output:type_name -> slowmo.RuntimeOutput
	3, // 1: slowmoexec.ExecResponse.runtime_result:type_name -> slowmo.RuntimeResult
	0, // 2: slowmoexec.ExecService.Exec:input_type -> slowmoexec.ExecRequest
	1, // 3: slowmoexec.ExecService.Exec:output_type -> slowmoexec.ExecResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_exec_proto_init() }
func file_exec_proto_init() {
	if File_exec_proto != nil {
		return
	}
	file_slowmo_proto_init()
	file_exec_proto_msgTypes[0].OneofWrappers = []any{}
	file_exec_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecResponse_RuntimeOutput)(nil),
		(*ExecResponse_RuntimeResult)(nil),
		(*ExecResponse_Gomaxprocs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exec_proto_goTypes,
		DependencyIndexes: file_exec_proto_depIdxs,
		MessageInfos:      file_exec_proto_msgTypes,
	}.Build()
	File_exec_proto = out.File
	file_exec_proto_goTypes = nil
	file_exec_proto_depIdxs = nil
}
