/**
 * @fileoverview gRPC-Web generated client stub for slowmo
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: slowmo.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as slowmo_pb from './slowmo_pb'; // proto import: "slowmo.proto"


export class SlowmoServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCompileAndRun = new grpcWeb.MethodDescriptor(
    '/slowmo.SlowmoService/CompileAndRun',
    grpcWeb.MethodType.SERVER_STREAMING,
    slowmo_pb.CompileAndRunRequest,
    slowmo_pb.CompileAndRunResponse,
    (request: slowmo_pb.CompileAndRunRequest) => {
      return request.serializeBinary();
    },
    slowmo_pb.CompileAndRunResponse.deserializeBinary
  );

  compileAndRun(
    request: slowmo_pb.CompileAndRunRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<slowmo_pb.CompileAndRunResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/slowmo.SlowmoService/CompileAndRun',
      request,
      metadata || {},
      this.methodDescriptorCompileAndRun);
  }

}

