// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: slowmo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleReason int32

const (
	ScheduleReason_GOEXIT ScheduleReason = 0
	ScheduleReason_GOPARK ScheduleReason = 1
	ScheduleReason_MSTART ScheduleReason = 2
	ScheduleReason_OTHER  ScheduleReason = 20
)

// Enum value maps for ScheduleReason.
var (
	ScheduleReason_name = map[int32]string{
		0:  "GOEXIT",
		1:  "GOPARK",
		2:  "MSTART",
		20: "OTHER",
	}
	ScheduleReason_value = map[string]int32{
		"GOEXIT": 0,
		"GOPARK": 1,
		"MSTART": 2,
		"OTHER":  20,
	}
)

func (x ScheduleReason) Enum() *ScheduleReason {
	p := new(ScheduleReason)
	*p = x
	return p
}

func (x ScheduleReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleReason) Descriptor() protoreflect.EnumDescriptor {
	return file_slowmo_proto_enumTypes[0].Descriptor()
}

func (ScheduleReason) Type() protoreflect.EnumType {
	return &file_slowmo_proto_enumTypes[0]
}

func (x ScheduleReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleReason.Descriptor instead.
func (ScheduleReason) EnumDescriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{0}
}

type CompileAndRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *string                `protobuf:"bytes,1,opt,name=source,proto3,oneof" json:"source,omitempty"` // Go source code from user.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileAndRunRequest) Reset() {
	*x = CompileAndRunRequest{}
	mi := &file_slowmo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileAndRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileAndRunRequest) ProtoMessage() {}

func (x *CompileAndRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileAndRunRequest.ProtoReflect.Descriptor instead.
func (*CompileAndRunRequest) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{0}
}

func (x *CompileAndRunRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

type CompileAndRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CompileAndRunOneof:
	//
	//	*CompileAndRunResponse_CompileError
	//	*CompileAndRunResponse_RuntimeResult
	//	*CompileAndRunResponse_RunEvent
	//	*CompileAndRunResponse_RuntimeOutput
	//	*CompileAndRunResponse_Gomaxprocs
	CompileAndRunOneof isCompileAndRunResponse_CompileAndRunOneof `protobuf_oneof:"compile_and_run_oneof"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompileAndRunResponse) Reset() {
	*x = CompileAndRunResponse{}
	mi := &file_slowmo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileAndRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileAndRunResponse) ProtoMessage() {}

func (x *CompileAndRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileAndRunResponse.ProtoReflect.Descriptor instead.
func (*CompileAndRunResponse) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{1}
}

func (x *CompileAndRunResponse) GetCompileAndRunOneof() isCompileAndRunResponse_CompileAndRunOneof {
	if x != nil {
		return x.CompileAndRunOneof
	}
	return nil
}

func (x *CompileAndRunResponse) GetCompileError() *CompilationError {
	if x != nil {
		if x, ok := x.CompileAndRunOneof.(*CompileAndRunResponse_CompileError); ok {
			return x.CompileError
		}
	}
	return nil
}

func (x *CompileAndRunResponse) GetRuntimeResult() *RuntimeResult {
	if x != nil {
		if x, ok := x.CompileAndRunOneof.(*CompileAndRunResponse_RuntimeResult); ok {
			return x.RuntimeResult
		}
	}
	return nil
}

func (x *CompileAndRunResponse) GetRunEvent() *ProbeEvent {
	if x != nil {
		if x, ok := x.CompileAndRunOneof.(*CompileAndRunResponse_RunEvent); ok {
			return x.RunEvent
		}
	}
	return nil
}

func (x *CompileAndRunResponse) GetRuntimeOutput() *RuntimeOutput {
	if x != nil {
		if x, ok := x.CompileAndRunOneof.(*CompileAndRunResponse_RuntimeOutput); ok {
			return x.RuntimeOutput
		}
	}
	return nil
}

func (x *CompileAndRunResponse) GetGomaxprocs() int32 {
	if x != nil {
		if x, ok := x.CompileAndRunOneof.(*CompileAndRunResponse_Gomaxprocs); ok {
			return x.Gomaxprocs
		}
	}
	return 0
}

type isCompileAndRunResponse_CompileAndRunOneof interface {
	isCompileAndRunResponse_CompileAndRunOneof()
}

type CompileAndRunResponse_CompileError struct {
	CompileError *CompilationError `protobuf:"bytes,1,opt,name=compile_error,json=compileError,proto3,oneof"`
}

type CompileAndRunResponse_RuntimeResult struct {
	RuntimeResult *RuntimeResult `protobuf:"bytes,2,opt,name=runtime_result,json=runtimeResult,proto3,oneof"`
}

type CompileAndRunResponse_RunEvent struct {
	RunEvent *ProbeEvent `protobuf:"bytes,3,opt,name=run_event,json=runEvent,proto3,oneof"`
}

type CompileAndRunResponse_RuntimeOutput struct {
	RuntimeOutput *RuntimeOutput `protobuf:"bytes,4,opt,name=runtime_output,json=runtimeOutput,proto3,oneof"`
}

type CompileAndRunResponse_Gomaxprocs struct {
	Gomaxprocs int32 `protobuf:"varint,5,opt,name=gomaxprocs,proto3,oneof"`
}

func (*CompileAndRunResponse_CompileError) isCompileAndRunResponse_CompileAndRunOneof() {}

func (*CompileAndRunResponse_RuntimeResult) isCompileAndRunResponse_CompileAndRunOneof() {}

func (*CompileAndRunResponse_RunEvent) isCompileAndRunResponse_CompileAndRunOneof() {}

func (*CompileAndRunResponse_RuntimeOutput) isCompileAndRunResponse_CompileAndRunOneof() {}

func (*CompileAndRunResponse_Gomaxprocs) isCompileAndRunResponse_CompileAndRunOneof() {}

type CompilationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  *string                `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompilationError) Reset() {
	*x = CompilationError{}
	mi := &file_slowmo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompilationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilationError) ProtoMessage() {}

func (x *CompilationError) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilationError.ProtoReflect.Descriptor instead.
func (*CompilationError) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{2}
}

func (x *CompilationError) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type RuntimeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  *string                `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeResult) Reset() {
	*x = RuntimeResult{}
	mi := &file_slowmo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeResult) ProtoMessage() {}

func (x *RuntimeResult) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeResult.ProtoReflect.Descriptor instead.
func (*RuntimeResult) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeResult) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type RuntimeOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *string                `protobuf:"bytes,1,opt,name=output,proto3,oneof" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeOutput) Reset() {
	*x = RuntimeOutput{}
	mi := &file_slowmo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeOutput) ProtoMessage() {}

func (x *RuntimeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeOutput.ProtoReflect.Descriptor instead.
func (*RuntimeOutput) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeOutput) GetOutput() string {
	if x != nil && x.Output != nil {
		return *x.Output
	}
	return ""
}

type ProbeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ProbeEventOneof:
	//
	//	*ProbeEvent_DelayEvent
	//	*ProbeEvent_NotificationEvent
	//	*ProbeEvent_StructureStateEvent
	ProbeEventOneof isProbeEvent_ProbeEventOneof `protobuf_oneof:"probe_event_oneof"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProbeEvent) Reset() {
	*x = ProbeEvent{}
	mi := &file_slowmo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeEvent) ProtoMessage() {}

func (x *ProbeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeEvent.ProtoReflect.Descriptor instead.
func (*ProbeEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{5}
}

func (x *ProbeEvent) GetProbeEventOneof() isProbeEvent_ProbeEventOneof {
	if x != nil {
		return x.ProbeEventOneof
	}
	return nil
}

func (x *ProbeEvent) GetDelayEvent() *DelayEvent {
	if x != nil {
		if x, ok := x.ProbeEventOneof.(*ProbeEvent_DelayEvent); ok {
			return x.DelayEvent
		}
	}
	return nil
}

func (x *ProbeEvent) GetNotificationEvent() *NotificationEvent {
	if x != nil {
		if x, ok := x.ProbeEventOneof.(*ProbeEvent_NotificationEvent); ok {
			return x.NotificationEvent
		}
	}
	return nil
}

func (x *ProbeEvent) GetStructureStateEvent() *StructureStateEvent {
	if x != nil {
		if x, ok := x.ProbeEventOneof.(*ProbeEvent_StructureStateEvent); ok {
			return x.StructureStateEvent
		}
	}
	return nil
}

type isProbeEvent_ProbeEventOneof interface {
	isProbeEvent_ProbeEventOneof()
}

type ProbeEvent_DelayEvent struct {
	// RunqStatusEvent runq_status_event = 1 [deprecated=true];
	DelayEvent *DelayEvent `protobuf:"bytes,2,opt,name=delay_event,json=delayEvent,proto3,oneof"` // ScheduleEvent schedule_event = 3 [deprecated=true];
}

type ProbeEvent_NotificationEvent struct {
	NotificationEvent *NotificationEvent `protobuf:"bytes,4,opt,name=notification_event,json=notificationEvent,proto3,oneof"`
}

type ProbeEvent_StructureStateEvent struct {
	StructureStateEvent *StructureStateEvent `protobuf:"bytes,5,opt,name=structure_state_event,json=structureStateEvent,proto3,oneof"`
}

func (*ProbeEvent_DelayEvent) isProbeEvent_ProbeEventOneof() {}

func (*ProbeEvent_NotificationEvent) isProbeEvent_ProbeEventOneof() {}

func (*ProbeEvent_StructureStateEvent) isProbeEvent_ProbeEventOneof() {}

type NotificationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to NotificationOneof:
	//
	//	*NotificationEvent_ScheduleEvent
	//	*NotificationEvent_NewProcEvent
	//	*NotificationEvent_GoparkEvent
	NotificationOneof isNotificationEvent_NotificationOneof `protobuf_oneof:"notification_oneof"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotificationEvent) Reset() {
	*x = NotificationEvent{}
	mi := &file_slowmo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEvent) ProtoMessage() {}

func (x *NotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEvent.ProtoReflect.Descriptor instead.
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{6}
}

func (x *NotificationEvent) GetNotificationOneof() isNotificationEvent_NotificationOneof {
	if x != nil {
		return x.NotificationOneof
	}
	return nil
}

func (x *NotificationEvent) GetScheduleEvent() *ScheduleEvent {
	if x != nil {
		if x, ok := x.NotificationOneof.(*NotificationEvent_ScheduleEvent); ok {
			return x.ScheduleEvent
		}
	}
	return nil
}

func (x *NotificationEvent) GetNewProcEvent() *NewProcEvent {
	if x != nil {
		if x, ok := x.NotificationOneof.(*NotificationEvent_NewProcEvent); ok {
			return x.NewProcEvent
		}
	}
	return nil
}

func (x *NotificationEvent) GetGoparkEvent() *GoparkEvent {
	if x != nil {
		if x, ok := x.NotificationOneof.(*NotificationEvent_GoparkEvent); ok {
			return x.GoparkEvent
		}
	}
	return nil
}

type isNotificationEvent_NotificationOneof interface {
	isNotificationEvent_NotificationOneof()
}

type NotificationEvent_ScheduleEvent struct {
	// DelayEvent delay_event = 1 [deprecated=true];
	ScheduleEvent *ScheduleEvent `protobuf:"bytes,2,opt,name=schedule_event,json=scheduleEvent,proto3,oneof"`
}

type NotificationEvent_NewProcEvent struct {
	NewProcEvent *NewProcEvent `protobuf:"bytes,3,opt,name=new_proc_event,json=newProcEvent,proto3,oneof"`
}

type NotificationEvent_GoparkEvent struct {
	GoparkEvent *GoparkEvent `protobuf:"bytes,4,opt,name=gopark_event,json=goparkEvent,proto3,oneof"`
}

func (*NotificationEvent_ScheduleEvent) isNotificationEvent_NotificationOneof() {}

func (*NotificationEvent_NewProcEvent) isNotificationEvent_NotificationOneof() {}

func (*NotificationEvent_GoparkEvent) isNotificationEvent_NotificationOneof() {}

type StructureStateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to StructureStateOneof:
	//
	//	*StructureStateEvent_RunqStatusEvent
	//	*StructureStateEvent_ExecuteEvent
	//	*StructureStateEvent_GoreadyEvent
	StructureStateOneof isStructureStateEvent_StructureStateOneof `protobuf_oneof:"structure_state_oneof"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StructureStateEvent) Reset() {
	*x = StructureStateEvent{}
	mi := &file_slowmo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructureStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructureStateEvent) ProtoMessage() {}

func (x *StructureStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructureStateEvent.ProtoReflect.Descriptor instead.
func (*StructureStateEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{7}
}

func (x *StructureStateEvent) GetStructureStateOneof() isStructureStateEvent_StructureStateOneof {
	if x != nil {
		return x.StructureStateOneof
	}
	return nil
}

func (x *StructureStateEvent) GetRunqStatusEvent() *RunqStatusEvent {
	if x != nil {
		if x, ok := x.StructureStateOneof.(*StructureStateEvent_RunqStatusEvent); ok {
			return x.RunqStatusEvent
		}
	}
	return nil
}

func (x *StructureStateEvent) GetExecuteEvent() *ExecuteEvent {
	if x != nil {
		if x, ok := x.StructureStateOneof.(*StructureStateEvent_ExecuteEvent); ok {
			return x.ExecuteEvent
		}
	}
	return nil
}

func (x *StructureStateEvent) GetGoreadyEvent() *GoreadyEvent {
	if x != nil {
		if x, ok := x.StructureStateOneof.(*StructureStateEvent_GoreadyEvent); ok {
			return x.GoreadyEvent
		}
	}
	return nil
}

type isStructureStateEvent_StructureStateOneof interface {
	isStructureStateEvent_StructureStateOneof()
}

type StructureStateEvent_RunqStatusEvent struct {
	RunqStatusEvent *RunqStatusEvent `protobuf:"bytes,1,opt,name=runq_status_event,json=runqStatusEvent,proto3,oneof"`
}

type StructureStateEvent_ExecuteEvent struct {
	ExecuteEvent *ExecuteEvent `protobuf:"bytes,2,opt,name=execute_event,json=executeEvent,proto3,oneof"`
}

type StructureStateEvent_GoreadyEvent struct {
	GoreadyEvent *GoreadyEvent `protobuf:"bytes,3,opt,name=goready_event,json=goreadyEvent,proto3,oneof"`
}

func (*StructureStateEvent_RunqStatusEvent) isStructureStateEvent_StructureStateOneof() {}

func (*StructureStateEvent_ExecuteEvent) isStructureStateEvent_StructureStateOneof() {}

func (*StructureStateEvent_GoreadyEvent) isStructureStateEvent_StructureStateOneof() {}

type RunqStatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcId        *int64                 `protobuf:"varint,1,opt,name=proc_id,json=procId,proto3,oneof" json:"proc_id,omitempty"`
	RunqEntries   []*RunqEntry           `protobuf:"bytes,3,rep,name=runq_entries,json=runqEntries,proto3" json:"runq_entries,omitempty"`
	Runnext       *RunqEntry             `protobuf:"bytes,4,opt,name=runnext,proto3" json:"runnext,omitempty"`
	MId           *int64                 `protobuf:"varint,5,opt,name=m_id,json=mId,proto3,oneof" json:"m_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunqStatusEvent) Reset() {
	*x = RunqStatusEvent{}
	mi := &file_slowmo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunqStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunqStatusEvent) ProtoMessage() {}

func (x *RunqStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunqStatusEvent.ProtoReflect.Descriptor instead.
func (*RunqStatusEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{8}
}

func (x *RunqStatusEvent) GetProcId() int64 {
	if x != nil && x.ProcId != nil {
		return *x.ProcId
	}
	return 0
}

func (x *RunqStatusEvent) GetRunqEntries() []*RunqEntry {
	if x != nil {
		return x.RunqEntries
	}
	return nil
}

func (x *RunqStatusEvent) GetRunnext() *RunqEntry {
	if x != nil {
		return x.Runnext
	}
	return nil
}

func (x *RunqStatusEvent) GetMId() int64 {
	if x != nil && x.MId != nil {
		return *x.MId
	}
	return 0
}

type RunqEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GoId             *int64                 `protobuf:"varint,1,opt,name=go_id,json=goId,proto3,oneof" json:"go_id,omitempty"`
	ExecutionContext *InterpretedPC         `protobuf:"bytes,2,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunqEntry) Reset() {
	*x = RunqEntry{}
	mi := &file_slowmo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunqEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunqEntry) ProtoMessage() {}

func (x *RunqEntry) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunqEntry.ProtoReflect.Descriptor instead.
func (*RunqEntry) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{9}
}

func (x *RunqEntry) GetGoId() int64 {
	if x != nil && x.GoId != nil {
		return *x.GoId
	}
	return 0
}

func (x *RunqEntry) GetExecutionContext() *InterpretedPC {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type InterpretedPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *string                `protobuf:"bytes,1,opt,name=file,proto3,oneof" json:"file,omitempty"`
	Line          *int32                 `protobuf:"varint,2,opt,name=line,proto3,oneof" json:"line,omitempty"`
	Func          *string                `protobuf:"bytes,3,opt,name=func,proto3,oneof" json:"func,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterpretedPC) Reset() {
	*x = InterpretedPC{}
	mi := &file_slowmo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterpretedPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterpretedPC) ProtoMessage() {}

func (x *InterpretedPC) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterpretedPC.ProtoReflect.Descriptor instead.
func (*InterpretedPC) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{10}
}

func (x *InterpretedPC) GetFile() string {
	if x != nil && x.File != nil {
		return *x.File
	}
	return ""
}

func (x *InterpretedPC) GetLine() int32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *InterpretedPC) GetFunc() string {
	if x != nil && x.Func != nil {
		return *x.Func
	}
	return ""
}

type ExecuteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MId           *int64                 `protobuf:"varint,1,opt,name=m_id,json=mId,proto3,oneof" json:"m_id,omitempty"`
	Found         *RunqEntry             `protobuf:"bytes,2,opt,name=found,proto3" json:"found,omitempty"`
	ProcId        *int64                 `protobuf:"varint,3,opt,name=proc_id,json=procId,proto3,oneof" json:"proc_id,omitempty"`
	Runqs         []*RunqStatusEvent     `protobuf:"bytes,4,rep,name=runqs,proto3" json:"runqs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEvent) Reset() {
	*x = ExecuteEvent{}
	mi := &file_slowmo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEvent) ProtoMessage() {}

func (x *ExecuteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEvent.ProtoReflect.Descriptor instead.
func (*ExecuteEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteEvent) GetMId() int64 {
	if x != nil && x.MId != nil {
		return *x.MId
	}
	return 0
}

func (x *ExecuteEvent) GetFound() *RunqEntry {
	if x != nil {
		return x.Found
	}
	return nil
}

func (x *ExecuteEvent) GetProcId() int64 {
	if x != nil && x.ProcId != nil {
		return *x.ProcId
	}
	return 0
}

func (x *ExecuteEvent) GetRunqs() []*RunqStatusEvent {
	if x != nil {
		return x.Runqs
	}
	return nil
}

type DelayEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MId           *int64                 `protobuf:"varint,1,opt,name=m_id,json=mId,proto3,oneof" json:"m_id,omitempty"`
	GoId          *int64                 `protobuf:"varint,2,opt,name=go_id,json=goId,proto3,oneof" json:"go_id,omitempty"`
	CurrentPc     *InterpretedPC         `protobuf:"bytes,3,opt,name=current_pc,json=currentPc,proto3" json:"current_pc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayEvent) Reset() {
	*x = DelayEvent{}
	mi := &file_slowmo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayEvent) ProtoMessage() {}

func (x *DelayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayEvent.ProtoReflect.Descriptor instead.
func (*DelayEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{12}
}

func (x *DelayEvent) GetMId() int64 {
	if x != nil && x.MId != nil {
		return *x.MId
	}
	return 0
}

func (x *DelayEvent) GetGoId() int64 {
	if x != nil && x.GoId != nil {
		return *x.GoId
	}
	return 0
}

func (x *DelayEvent) GetCurrentPc() *InterpretedPC {
	if x != nil {
		return x.CurrentPc
	}
	return nil
}

type ScheduleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MId           *int64                 `protobuf:"varint,1,opt,name=m_id,json=mId,proto3,oneof" json:"m_id,omitempty"`
	Reason        ScheduleReason         `protobuf:"varint,2,opt,name=reason,proto3,enum=slowmo.ScheduleReason" json:"reason,omitempty"`
	ProcId        *int64                 `protobuf:"varint,3,opt,name=proc_id,json=procId,proto3,oneof" json:"proc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEvent) Reset() {
	*x = ScheduleEvent{}
	mi := &file_slowmo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEvent) ProtoMessage() {}

func (x *ScheduleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEvent.ProtoReflect.Descriptor instead.
func (*ScheduleEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{13}
}

func (x *ScheduleEvent) GetMId() int64 {
	if x != nil && x.MId != nil {
		return *x.MId
	}
	return 0
}

func (x *ScheduleEvent) GetReason() ScheduleReason {
	if x != nil {
		return x.Reason
	}
	return ScheduleReason_GOEXIT
}

func (x *ScheduleEvent) GetProcId() int64 {
	if x != nil && x.ProcId != nil {
		return *x.ProcId
	}
	return 0
}

type NewProcEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorGoId   *int64                 `protobuf:"varint,1,opt,name=creator_go_id,json=creatorGoId,proto3,oneof" json:"creator_go_id,omitempty"`
	StartPc       *InterpretedPC         `protobuf:"bytes,2,opt,name=start_pc,json=startPc,proto3" json:"start_pc,omitempty"`
	MId           *int64                 `protobuf:"varint,3,opt,name=m_id,json=mId,proto3,oneof" json:"m_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewProcEvent) Reset() {
	*x = NewProcEvent{}
	mi := &file_slowmo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewProcEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProcEvent) ProtoMessage() {}

func (x *NewProcEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProcEvent.ProtoReflect.Descriptor instead.
func (*NewProcEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{14}
}

func (x *NewProcEvent) GetCreatorGoId() int64 {
	if x != nil && x.CreatorGoId != nil {
		return *x.CreatorGoId
	}
	return 0
}

func (x *NewProcEvent) GetStartPc() *InterpretedPC {
	if x != nil {
		return x.StartPc
	}
	return nil
}

func (x *NewProcEvent) GetMId() int64 {
	if x != nil && x.MId != nil {
		return *x.MId
	}
	return 0
}

type GoparkEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MId           *int64                 `protobuf:"varint,1,opt,name=m_id,json=mId,proto3,oneof" json:"m_id,omitempty"`
	Parked        *RunqEntry             `protobuf:"bytes,2,opt,name=parked,proto3" json:"parked,omitempty"`
	WaitReason    *string                `protobuf:"bytes,3,opt,name=wait_reason,json=waitReason,proto3,oneof" json:"wait_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoparkEvent) Reset() {
	*x = GoparkEvent{}
	mi := &file_slowmo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoparkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoparkEvent) ProtoMessage() {}

func (x *GoparkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoparkEvent.ProtoReflect.Descriptor instead.
func (*GoparkEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{15}
}

func (x *GoparkEvent) GetMId() int64 {
	if x != nil && x.MId != nil {
		return *x.MId
	}
	return 0
}

func (x *GoparkEvent) GetParked() *RunqEntry {
	if x != nil {
		return x.Parked
	}
	return nil
}

func (x *GoparkEvent) GetWaitReason() string {
	if x != nil && x.WaitReason != nil {
		return *x.WaitReason
	}
	return ""
}

type GoreadyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MId           *int64                 `protobuf:"varint,1,opt,name=m_id,json=mId,proto3,oneof" json:"m_id,omitempty"`
	GoId          *int64                 `protobuf:"varint,2,opt,name=go_id,json=goId,proto3,oneof" json:"go_id,omitempty"`
	Runq          *RunqStatusEvent       `protobuf:"bytes,3,opt,name=runq,proto3" json:"runq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoreadyEvent) Reset() {
	*x = GoreadyEvent{}
	mi := &file_slowmo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoreadyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoreadyEvent) ProtoMessage() {}

func (x *GoreadyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoreadyEvent.ProtoReflect.Descriptor instead.
func (*GoreadyEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{16}
}

func (x *GoreadyEvent) GetMId() int64 {
	if x != nil && x.MId != nil {
		return *x.MId
	}
	return 0
}

func (x *GoreadyEvent) GetGoId() int64 {
	if x != nil && x.GoId != nil {
		return *x.GoId
	}
	return 0
}

func (x *GoreadyEvent) GetRunq() *RunqStatusEvent {
	if x != nil {
		return x.Runq
	}
	return nil
}

var File_slowmo_proto protoreflect.FileDescriptor

const file_slowmo_proto_rawDesc = "" +
	"\n" +
	"\fslowmo.proto\x12\x06slowmo\">\n" +
	"\x14CompileAndRunRequest\x12\x1b\n" +
	"\x06source\x18\x01 \x01(\tH\x00R\x06source\x88\x01\x01B\t\n" +
	"\a_source\"\xc6\x02\n" +
	"\x15CompileAndRunResponse\x12?\n" +
	"\rcompile_error\x18\x01 \x01(\v2\x18.slowmo.CompilationErrorH\x00R\fcompileError\x12>\n" +
	"\x0eruntime_result\x18\x02 \x01(\v2\x15.slowmo.RuntimeResultH\x00R\rruntimeResult\x121\n" +
	"\trun_event\x18\x03 \x01(\v2\x12.slowmo.ProbeEventH\x00R\brunEvent\x12>\n" +
	"\x0eruntime_output\x18\x04 \x01(\v2\x15.slowmo.RuntimeOutputH\x00R\rruntimeOutput\x12 \n" +
	"\n" +
	"gomaxprocs\x18\x05 \x01(\x05H\x00R\n" +
	"gomaxprocsB\x17\n" +
	"\x15compile_and_run_oneof\"N\n" +
	"\x10CompilationError\x12(\n" +
	"\rerror_message\x18\x01 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"K\n" +
	"\rRuntimeResult\x12(\n" +
	"\rerror_message\x18\x01 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"7\n" +
	"\rRuntimeOutput\x12\x1b\n" +
	"\x06output\x18\x01 \x01(\tH\x00R\x06output\x88\x01\x01B\t\n" +
	"\a_output\"\xf7\x01\n" +
	"\n" +
	"ProbeEvent\x125\n" +
	"\vdelay_event\x18\x02 \x01(\v2\x12.slowmo.DelayEventH\x00R\n" +
	"delayEvent\x12J\n" +
	"\x12notification_event\x18\x04 \x01(\v2\x19.slowmo.NotificationEventH\x00R\x11notificationEvent\x12Q\n" +
	"\x15structure_state_event\x18\x05 \x01(\v2\x1b.slowmo.StructureStateEventH\x00R\x13structureStateEventB\x13\n" +
	"\x11probe_event_oneof\"\xe1\x01\n" +
	"\x11NotificationEvent\x12>\n" +
	"\x0eschedule_event\x18\x02 \x01(\v2\x15.slowmo.ScheduleEventH\x00R\rscheduleEvent\x12<\n" +
	"\x0enew_proc_event\x18\x03 \x01(\v2\x14.slowmo.NewProcEventH\x00R\fnewProcEvent\x128\n" +
	"\fgopark_event\x18\x04 \x01(\v2\x13.slowmo.GoparkEventH\x00R\vgoparkEventB\x14\n" +
	"\x12notification_oneof\"\xef\x01\n" +
	"\x13StructureStateEvent\x12E\n" +
	"\x11runq_status_event\x18\x01 \x01(\v2\x17.slowmo.RunqStatusEventH\x00R\x0frunqStatusEvent\x12;\n" +
	"\rexecute_event\x18\x02 \x01(\v2\x14.slowmo.ExecuteEventH\x00R\fexecuteEvent\x12;\n" +
	"\rgoready_event\x18\x03 \x01(\v2\x14.slowmo.GoreadyEventH\x00R\fgoreadyEventB\x17\n" +
	"\x15structure_state_oneof\"\xbf\x01\n" +
	"\x0fRunqStatusEvent\x12\x1c\n" +
	"\aproc_id\x18\x01 \x01(\x03H\x00R\x06procId\x88\x01\x01\x124\n" +
	"\frunq_entries\x18\x03 \x03(\v2\x11.slowmo.RunqEntryR\vrunqEntries\x12+\n" +
	"\arunnext\x18\x04 \x01(\v2\x11.slowmo.RunqEntryR\arunnext\x12\x16\n" +
	"\x04m_id\x18\x05 \x01(\x03H\x01R\x03mId\x88\x01\x01B\n" +
	"\n" +
	"\b_proc_idB\a\n" +
	"\x05_m_id\"s\n" +
	"\tRunqEntry\x12\x18\n" +
	"\x05go_id\x18\x01 \x01(\x03H\x00R\x04goId\x88\x01\x01\x12B\n" +
	"\x11execution_context\x18\x02 \x01(\v2\x15.slowmo.InterpretedPCR\x10executionContextB\b\n" +
	"\x06_go_id\"u\n" +
	"\rInterpretedPC\x12\x17\n" +
	"\x04file\x18\x01 \x01(\tH\x00R\x04file\x88\x01\x01\x12\x17\n" +
	"\x04line\x18\x02 \x01(\x05H\x01R\x04line\x88\x01\x01\x12\x17\n" +
	"\x04func\x18\x03 \x01(\tH\x02R\x04func\x88\x01\x01B\a\n" +
	"\x05_fileB\a\n" +
	"\x05_lineB\a\n" +
	"\x05_func\"\xb1\x01\n" +
	"\fExecuteEvent\x12\x16\n" +
	"\x04m_id\x18\x01 \x01(\x03H\x00R\x03mId\x88\x01\x01\x12'\n" +
	"\x05found\x18\x02 \x01(\v2\x11.slowmo.RunqEntryR\x05found\x12\x1c\n" +
	"\aproc_id\x18\x03 \x01(\x03H\x01R\x06procId\x88\x01\x01\x12-\n" +
	"\x05runqs\x18\x04 \x03(\v2\x17.slowmo.RunqStatusEventR\x05runqsB\a\n" +
	"\x05_m_idB\n" +
	"\n" +
	"\b_proc_id\"\x87\x01\n" +
	"\n" +
	"DelayEvent\x12\x16\n" +
	"\x04m_id\x18\x01 \x01(\x03H\x00R\x03mId\x88\x01\x01\x12\x18\n" +
	"\x05go_id\x18\x02 \x01(\x03H\x01R\x04goId\x88\x01\x01\x124\n" +
	"\n" +
	"current_pc\x18\x03 \x01(\v2\x15.slowmo.InterpretedPCR\tcurrentPcB\a\n" +
	"\x05_m_idB\b\n" +
	"\x06_go_id\"\x8a\x01\n" +
	"\rScheduleEvent\x12\x16\n" +
	"\x04m_id\x18\x01 \x01(\x03H\x00R\x03mId\x88\x01\x01\x12.\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x16.slowmo.ScheduleReasonR\x06reason\x12\x1c\n" +
	"\aproc_id\x18\x03 \x01(\x03H\x01R\x06procId\x88\x01\x01B\a\n" +
	"\x05_m_idB\n" +
	"\n" +
	"\b_proc_id\"\x9c\x01\n" +
	"\fNewProcEvent\x12'\n" +
	"\rcreator_go_id\x18\x01 \x01(\x03H\x00R\vcreatorGoId\x88\x01\x01\x120\n" +
	"\bstart_pc\x18\x02 \x01(\v2\x15.slowmo.InterpretedPCR\astartPc\x12\x16\n" +
	"\x04m_id\x18\x03 \x01(\x03H\x01R\x03mId\x88\x01\x01B\x10\n" +
	"\x0e_creator_go_idB\a\n" +
	"\x05_m_id\"\x8f\x01\n" +
	"\vGoparkEvent\x12\x16\n" +
	"\x04m_id\x18\x01 \x01(\x03H\x00R\x03mId\x88\x01\x01\x12)\n" +
	"\x06parked\x18\x02 \x01(\v2\x11.slowmo.RunqEntryR\x06parked\x12$\n" +
	"\vwait_reason\x18\x03 \x01(\tH\x01R\n" +
	"waitReason\x88\x01\x01B\a\n" +
	"\x05_m_idB\x0e\n" +
	"\f_wait_reason\"\x80\x01\n" +
	"\fGoreadyEvent\x12\x16\n" +
	"\x04m_id\x18\x01 \x01(\x03H\x00R\x03mId\x88\x01\x01\x12\x18\n" +
	"\x05go_id\x18\x02 \x01(\x03H\x01R\x04goId\x88\x01\x01\x12+\n" +
	"\x04runq\x18\x03 \x01(\v2\x17.slowmo.RunqStatusEventR\x04runqB\a\n" +
	"\x05_m_idB\b\n" +
	"\x06_go_id*?\n" +
	"\x0eScheduleReason\x12\n" +
	"\n" +
	"\x06GOEXIT\x10\x00\x12\n" +
	"\n" +
	"\x06GOPARK\x10\x01\x12\n" +
	"\n" +
	"\x06MSTART\x10\x02\x12\t\n" +
	"\x05OTHER\x10\x142_\n" +
	"\rSlowmoService\x12N\n" +
	"\rCompileAndRun\x12\x1c.slowmo.CompileAndRunRequest\x1a\x1d.slowmo.CompileAndRunResponse0\x01B$Z\"github.com/kailun2047/slowmo/protob\x06proto3"

var (
	file_slowmo_proto_rawDescOnce sync.Once
	file_slowmo_proto_rawDescData []byte
)

func file_slowmo_proto_rawDescGZIP() []byte {
	file_slowmo_proto_rawDescOnce.Do(func() {
		file_slowmo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slowmo_proto_rawDesc), len(file_slowmo_proto_rawDesc)))
	})
	return file_slowmo_proto_rawDescData
}

var file_slowmo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_slowmo_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_slowmo_proto_goTypes = []any{
	(ScheduleReason)(0),           // 0: slowmo.ScheduleReason
	(*CompileAndRunRequest)(nil),  // 1: slowmo.CompileAndRunRequest
	(*CompileAndRunResponse)(nil), // 2: slowmo.CompileAndRunResponse
	(*CompilationError)(nil),      // 3: slowmo.CompilationError
	(*RuntimeResult)(nil),         // 4: slowmo.RuntimeResult
	(*RuntimeOutput)(nil),         // 5: slowmo.RuntimeOutput
	(*ProbeEvent)(nil),            // 6: slowmo.ProbeEvent
	(*NotificationEvent)(nil),     // 7: slowmo.NotificationEvent
	(*StructureStateEvent)(nil),   // 8: slowmo.StructureStateEvent
	(*RunqStatusEvent)(nil),       // 9: slowmo.RunqStatusEvent
	(*RunqEntry)(nil),             // 10: slowmo.RunqEntry
	(*InterpretedPC)(nil),         // 11: slowmo.InterpretedPC
	(*ExecuteEvent)(nil),          // 12: slowmo.ExecuteEvent
	(*DelayEvent)(nil),            // 13: slowmo.DelayEvent
	(*ScheduleEvent)(nil),         // 14: slowmo.ScheduleEvent
	(*NewProcEvent)(nil),          // 15: slowmo.NewProcEvent
	(*GoparkEvent)(nil),           // 16: slowmo.GoparkEvent
	(*GoreadyEvent)(nil),          // 17: slowmo.GoreadyEvent
}
var file_slowmo_proto_depIdxs = []int32{
	3,  // 0: slowmo.CompileAndRunResponse.compile_error:type_name -> slowmo.CompilationError
	4,  // 1: slowmo.CompileAndRunResponse.runtime_result:type_name -> slowmo.RuntimeResult
	6,  // 2: slowmo.CompileAndRunResponse.run_event:type_name -> slowmo.ProbeEvent
	5,  // 3: slowmo.CompileAndRunResponse.runtime_output:type_name -> slowmo.RuntimeOutput
	13, // 4: slowmo.ProbeEvent.delay_event:type_name -> slowmo.DelayEvent
	7,  // 5: slowmo.ProbeEvent.notification_event:type_name -> slowmo.NotificationEvent
	8,  // 6: slowmo.ProbeEvent.structure_state_event:type_name -> slowmo.StructureStateEvent
	14, // 7: slowmo.NotificationEvent.schedule_event:type_name -> slowmo.ScheduleEvent
	15, // 8: slowmo.NotificationEvent.new_proc_event:type_name -> slowmo.NewProcEvent
	16, // 9: slowmo.NotificationEvent.gopark_event:type_name -> slowmo.GoparkEvent
	9,  // 10: slowmo.StructureStateEvent.runq_status_event:type_name -> slowmo.RunqStatusEvent
	12, // 11: slowmo.StructureStateEvent.execute_event:type_name -> slowmo.ExecuteEvent
	17, // 12: slowmo.StructureStateEvent.goready_event:type_name -> slowmo.GoreadyEvent
	10, // 13: slowmo.RunqStatusEvent.runq_entries:type_name -> slowmo.RunqEntry
	10, // 14: slowmo.RunqStatusEvent.runnext:type_name -> slowmo.RunqEntry
	11, // 15: slowmo.RunqEntry.execution_context:type_name -> slowmo.InterpretedPC
	10, // 16: slowmo.ExecuteEvent.found:type_name -> slowmo.RunqEntry
	9,  // 17: slowmo.ExecuteEvent.runqs:type_name -> slowmo.RunqStatusEvent
	11, // 18: slowmo.DelayEvent.current_pc:type_name -> slowmo.InterpretedPC
	0,  // 19: slowmo.ScheduleEvent.reason:type_name -> slowmo.ScheduleReason
	11, // 20: slowmo.NewProcEvent.start_pc:type_name -> slowmo.InterpretedPC
	10, // 21: slowmo.GoparkEvent.parked:type_name -> slowmo.RunqEntry
	9,  // 22: slowmo.GoreadyEvent.runq:type_name -> slowmo.RunqStatusEvent
	1,  // 23: slowmo.SlowmoService.CompileAndRun:input_type -> slowmo.CompileAndRunRequest
	2,  // 24: slowmo.SlowmoService.CompileAndRun:output_type -> slowmo.CompileAndRunResponse
	24, // [24:25] is the sub-list for method output_type
	23, // [23:24] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_slowmo_proto_init() }
func file_slowmo_proto_init() {
	if File_slowmo_proto != nil {
		return
	}
	file_slowmo_proto_msgTypes[0].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[1].OneofWrappers = []any{
		(*CompileAndRunResponse_CompileError)(nil),
		(*CompileAndRunResponse_RuntimeResult)(nil),
		(*CompileAndRunResponse_RunEvent)(nil),
		(*CompileAndRunResponse_RuntimeOutput)(nil),
		(*CompileAndRunResponse_Gomaxprocs)(nil),
	}
	file_slowmo_proto_msgTypes[2].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[3].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[4].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[5].OneofWrappers = []any{
		(*ProbeEvent_DelayEvent)(nil),
		(*ProbeEvent_NotificationEvent)(nil),
		(*ProbeEvent_StructureStateEvent)(nil),
	}
	file_slowmo_proto_msgTypes[6].OneofWrappers = []any{
		(*NotificationEvent_ScheduleEvent)(nil),
		(*NotificationEvent_NewProcEvent)(nil),
		(*NotificationEvent_GoparkEvent)(nil),
	}
	file_slowmo_proto_msgTypes[7].OneofWrappers = []any{
		(*StructureStateEvent_RunqStatusEvent)(nil),
		(*StructureStateEvent_ExecuteEvent)(nil),
		(*StructureStateEvent_GoreadyEvent)(nil),
	}
	file_slowmo_proto_msgTypes[8].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[9].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[10].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[11].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[12].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[13].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[14].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[15].OneofWrappers = []any{}
	file_slowmo_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slowmo_proto_rawDesc), len(file_slowmo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slowmo_proto_goTypes,
		DependencyIndexes: file_slowmo_proto_depIdxs,
		EnumInfos:         file_slowmo_proto_enumTypes,
		MessageInfos:      file_slowmo_proto_msgTypes,
	}.Build()
	File_slowmo_proto = out.File
	file_slowmo_proto_goTypes = nil
	file_slowmo_proto_depIdxs = nil
}
