// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: slowmo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SlowmoService_CompileAndRun_FullMethodName = "/slowmo.SlowmoService/CompileAndRun"
	SlowmoService_Authn_FullMethodName         = "/slowmo.SlowmoService/Authn"
)

// SlowmoServiceClient is the client API for SlowmoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlowmoServiceClient interface {
	CompileAndRun(ctx context.Context, in *CompileAndRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompileAndRunResponse], error)
	Authn(ctx context.Context, in *AuthnRequest, opts ...grpc.CallOption) (*AuthnResponse, error)
}

type slowmoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSlowmoServiceClient(cc grpc.ClientConnInterface) SlowmoServiceClient {
	return &slowmoServiceClient{cc}
}

func (c *slowmoServiceClient) CompileAndRun(ctx context.Context, in *CompileAndRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompileAndRunResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SlowmoService_ServiceDesc.Streams[0], SlowmoService_CompileAndRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompileAndRunRequest, CompileAndRunResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SlowmoService_CompileAndRunClient = grpc.ServerStreamingClient[CompileAndRunResponse]

func (c *slowmoServiceClient) Authn(ctx context.Context, in *AuthnRequest, opts ...grpc.CallOption) (*AuthnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthnResponse)
	err := c.cc.Invoke(ctx, SlowmoService_Authn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlowmoServiceServer is the server API for SlowmoService service.
// All implementations must embed UnimplementedSlowmoServiceServer
// for forward compatibility.
type SlowmoServiceServer interface {
	CompileAndRun(*CompileAndRunRequest, grpc.ServerStreamingServer[CompileAndRunResponse]) error
	Authn(context.Context, *AuthnRequest) (*AuthnResponse, error)
	mustEmbedUnimplementedSlowmoServiceServer()
}

// UnimplementedSlowmoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSlowmoServiceServer struct{}

func (UnimplementedSlowmoServiceServer) CompileAndRun(*CompileAndRunRequest, grpc.ServerStreamingServer[CompileAndRunResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CompileAndRun not implemented")
}
func (UnimplementedSlowmoServiceServer) Authn(context.Context, *AuthnRequest) (*AuthnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authn not implemented")
}
func (UnimplementedSlowmoServiceServer) mustEmbedUnimplementedSlowmoServiceServer() {}
func (UnimplementedSlowmoServiceServer) testEmbeddedByValue()                       {}

// UnsafeSlowmoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlowmoServiceServer will
// result in compilation errors.
type UnsafeSlowmoServiceServer interface {
	mustEmbedUnimplementedSlowmoServiceServer()
}

func RegisterSlowmoServiceServer(s grpc.ServiceRegistrar, srv SlowmoServiceServer) {
	// If the following call pancis, it indicates UnimplementedSlowmoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SlowmoService_ServiceDesc, srv)
}

func _SlowmoService_CompileAndRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompileAndRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SlowmoServiceServer).CompileAndRun(m, &grpc.GenericServerStream[CompileAndRunRequest, CompileAndRunResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SlowmoService_CompileAndRunServer = grpc.ServerStreamingServer[CompileAndRunResponse]

func _SlowmoService_Authn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlowmoServiceServer).Authn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlowmoService_Authn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlowmoServiceServer).Authn(ctx, req.(*AuthnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SlowmoService_ServiceDesc is the grpc.ServiceDesc for SlowmoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlowmoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slowmo.SlowmoService",
	HandlerType: (*SlowmoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authn",
			Handler:    _SlowmoService_Authn_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CompileAndRun",
			Handler:       _SlowmoService_CompileAndRun_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "slowmo.proto",
}
