// source: slowmo.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.slowmo.CompilationError', null, global);
goog.exportSymbol('proto.slowmo.CompileAndRunRequest', null, global);
goog.exportSymbol('proto.slowmo.CompileAndRunResponse', null, global);
goog.exportSymbol('proto.slowmo.CompileAndRunResponse.CompileAndRunOneofCase', null, global);
goog.exportSymbol('proto.slowmo.InterpretedPC', null, global);
goog.exportSymbol('proto.slowmo.ProbeEvent', null, global);
goog.exportSymbol('proto.slowmo.ProbeEvent.ProbeEventOneofCase', null, global);
goog.exportSymbol('proto.slowmo.RunqEntry', null, global);
goog.exportSymbol('proto.slowmo.RunqStatusEvent', null, global);
goog.exportSymbol('proto.slowmo.RuntimeError', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.slowmo.CompileAndRunRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.slowmo.CompileAndRunRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.slowmo.CompileAndRunRequest.displayName = 'proto.slowmo.CompileAndRunRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.slowmo.CompileAndRunResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.slowmo.CompileAndRunResponse.oneofGroups_);
};
goog.inherits(proto.slowmo.CompileAndRunResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.slowmo.CompileAndRunResponse.displayName = 'proto.slowmo.CompileAndRunResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.slowmo.CompilationError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.slowmo.CompilationError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.slowmo.CompilationError.displayName = 'proto.slowmo.CompilationError';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.slowmo.RuntimeError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.slowmo.RuntimeError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.slowmo.RuntimeError.displayName = 'proto.slowmo.RuntimeError';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.slowmo.ProbeEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.slowmo.ProbeEvent.oneofGroups_);
};
goog.inherits(proto.slowmo.ProbeEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.slowmo.ProbeEvent.displayName = 'proto.slowmo.ProbeEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.slowmo.RunqStatusEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.slowmo.RunqStatusEvent.repeatedFields_, null);
};
goog.inherits(proto.slowmo.RunqStatusEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.slowmo.RunqStatusEvent.displayName = 'proto.slowmo.RunqStatusEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.slowmo.InterpretedPC = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.slowmo.InterpretedPC, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.slowmo.InterpretedPC.displayName = 'proto.slowmo.InterpretedPC';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.slowmo.RunqEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.slowmo.RunqEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.slowmo.RunqEntry.displayName = 'proto.slowmo.RunqEntry';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.slowmo.CompileAndRunRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.slowmo.CompileAndRunRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.slowmo.CompileAndRunRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.CompileAndRunRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    source: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.slowmo.CompileAndRunRequest}
 */
proto.slowmo.CompileAndRunRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.slowmo.CompileAndRunRequest;
  return proto.slowmo.CompileAndRunRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.slowmo.CompileAndRunRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.slowmo.CompileAndRunRequest}
 */
proto.slowmo.CompileAndRunRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.slowmo.CompileAndRunRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.slowmo.CompileAndRunRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.slowmo.CompileAndRunRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.CompileAndRunRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string source = 1;
 * @return {string}
 */
proto.slowmo.CompileAndRunRequest.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.slowmo.CompileAndRunRequest} returns this
 */
proto.slowmo.CompileAndRunRequest.prototype.setSource = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.slowmo.CompileAndRunResponse.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.slowmo.CompileAndRunResponse.CompileAndRunOneofCase = {
  COMPILE_AND_RUN_ONEOF_NOT_SET: 0,
  COMPILE_ERROR: 1,
  RUNTIME_ERROR: 2,
  RUN_EVENT: 3
};

/**
 * @return {proto.slowmo.CompileAndRunResponse.CompileAndRunOneofCase}
 */
proto.slowmo.CompileAndRunResponse.prototype.getCompileAndRunOneofCase = function() {
  return /** @type {proto.slowmo.CompileAndRunResponse.CompileAndRunOneofCase} */(jspb.Message.computeOneofCase(this, proto.slowmo.CompileAndRunResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.slowmo.CompileAndRunResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.slowmo.CompileAndRunResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.slowmo.CompileAndRunResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.CompileAndRunResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    compileError: (f = msg.getCompileError()) && proto.slowmo.CompilationError.toObject(includeInstance, f),
    runtimeError: (f = msg.getRuntimeError()) && proto.slowmo.RuntimeError.toObject(includeInstance, f),
    runEvent: (f = msg.getRunEvent()) && proto.slowmo.ProbeEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.slowmo.CompileAndRunResponse}
 */
proto.slowmo.CompileAndRunResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.slowmo.CompileAndRunResponse;
  return proto.slowmo.CompileAndRunResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.slowmo.CompileAndRunResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.slowmo.CompileAndRunResponse}
 */
proto.slowmo.CompileAndRunResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.slowmo.CompilationError;
      reader.readMessage(value,proto.slowmo.CompilationError.deserializeBinaryFromReader);
      msg.setCompileError(value);
      break;
    case 2:
      var value = new proto.slowmo.RuntimeError;
      reader.readMessage(value,proto.slowmo.RuntimeError.deserializeBinaryFromReader);
      msg.setRuntimeError(value);
      break;
    case 3:
      var value = new proto.slowmo.ProbeEvent;
      reader.readMessage(value,proto.slowmo.ProbeEvent.deserializeBinaryFromReader);
      msg.setRunEvent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.slowmo.CompileAndRunResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.slowmo.CompileAndRunResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.slowmo.CompileAndRunResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.CompileAndRunResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCompileError();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.slowmo.CompilationError.serializeBinaryToWriter
    );
  }
  f = message.getRuntimeError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.slowmo.RuntimeError.serializeBinaryToWriter
    );
  }
  f = message.getRunEvent();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.slowmo.ProbeEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional CompilationError compile_error = 1;
 * @return {?proto.slowmo.CompilationError}
 */
proto.slowmo.CompileAndRunResponse.prototype.getCompileError = function() {
  return /** @type{?proto.slowmo.CompilationError} */ (
    jspb.Message.getWrapperField(this, proto.slowmo.CompilationError, 1));
};


/**
 * @param {?proto.slowmo.CompilationError|undefined} value
 * @return {!proto.slowmo.CompileAndRunResponse} returns this
*/
proto.slowmo.CompileAndRunResponse.prototype.setCompileError = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.slowmo.CompileAndRunResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.slowmo.CompileAndRunResponse} returns this
 */
proto.slowmo.CompileAndRunResponse.prototype.clearCompileError = function() {
  return this.setCompileError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.slowmo.CompileAndRunResponse.prototype.hasCompileError = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional RuntimeError runtime_error = 2;
 * @return {?proto.slowmo.RuntimeError}
 */
proto.slowmo.CompileAndRunResponse.prototype.getRuntimeError = function() {
  return /** @type{?proto.slowmo.RuntimeError} */ (
    jspb.Message.getWrapperField(this, proto.slowmo.RuntimeError, 2));
};


/**
 * @param {?proto.slowmo.RuntimeError|undefined} value
 * @return {!proto.slowmo.CompileAndRunResponse} returns this
*/
proto.slowmo.CompileAndRunResponse.prototype.setRuntimeError = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.slowmo.CompileAndRunResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.slowmo.CompileAndRunResponse} returns this
 */
proto.slowmo.CompileAndRunResponse.prototype.clearRuntimeError = function() {
  return this.setRuntimeError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.slowmo.CompileAndRunResponse.prototype.hasRuntimeError = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ProbeEvent run_event = 3;
 * @return {?proto.slowmo.ProbeEvent}
 */
proto.slowmo.CompileAndRunResponse.prototype.getRunEvent = function() {
  return /** @type{?proto.slowmo.ProbeEvent} */ (
    jspb.Message.getWrapperField(this, proto.slowmo.ProbeEvent, 3));
};


/**
 * @param {?proto.slowmo.ProbeEvent|undefined} value
 * @return {!proto.slowmo.CompileAndRunResponse} returns this
*/
proto.slowmo.CompileAndRunResponse.prototype.setRunEvent = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.slowmo.CompileAndRunResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.slowmo.CompileAndRunResponse} returns this
 */
proto.slowmo.CompileAndRunResponse.prototype.clearRunEvent = function() {
  return this.setRunEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.slowmo.CompileAndRunResponse.prototype.hasRunEvent = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.slowmo.CompilationError.prototype.toObject = function(opt_includeInstance) {
  return proto.slowmo.CompilationError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.slowmo.CompilationError} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.CompilationError.toObject = function(includeInstance, msg) {
  var f, obj = {
    errorMessage: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.slowmo.CompilationError}
 */
proto.slowmo.CompilationError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.slowmo.CompilationError;
  return proto.slowmo.CompilationError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.slowmo.CompilationError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.slowmo.CompilationError}
 */
proto.slowmo.CompilationError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.slowmo.CompilationError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.slowmo.CompilationError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.slowmo.CompilationError} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.CompilationError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrorMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string error_message = 1;
 * @return {string}
 */
proto.slowmo.CompilationError.prototype.getErrorMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.slowmo.CompilationError} returns this
 */
proto.slowmo.CompilationError.prototype.setErrorMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.slowmo.RuntimeError.prototype.toObject = function(opt_includeInstance) {
  return proto.slowmo.RuntimeError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.slowmo.RuntimeError} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.RuntimeError.toObject = function(includeInstance, msg) {
  var f, obj = {
    errorMessage: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.slowmo.RuntimeError}
 */
proto.slowmo.RuntimeError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.slowmo.RuntimeError;
  return proto.slowmo.RuntimeError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.slowmo.RuntimeError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.slowmo.RuntimeError}
 */
proto.slowmo.RuntimeError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.slowmo.RuntimeError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.slowmo.RuntimeError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.slowmo.RuntimeError} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.RuntimeError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrorMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string error_message = 1;
 * @return {string}
 */
proto.slowmo.RuntimeError.prototype.getErrorMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.slowmo.RuntimeError} returns this
 */
proto.slowmo.RuntimeError.prototype.setErrorMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.slowmo.ProbeEvent.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.slowmo.ProbeEvent.ProbeEventOneofCase = {
  PROBE_EVENT_ONEOF_NOT_SET: 0,
  RUNQ_STATUS_EVENT: 1
};

/**
 * @return {proto.slowmo.ProbeEvent.ProbeEventOneofCase}
 */
proto.slowmo.ProbeEvent.prototype.getProbeEventOneofCase = function() {
  return /** @type {proto.slowmo.ProbeEvent.ProbeEventOneofCase} */(jspb.Message.computeOneofCase(this, proto.slowmo.ProbeEvent.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.slowmo.ProbeEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.slowmo.ProbeEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.slowmo.ProbeEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.ProbeEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    runqStatusEvent: (f = msg.getRunqStatusEvent()) && proto.slowmo.RunqStatusEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.slowmo.ProbeEvent}
 */
proto.slowmo.ProbeEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.slowmo.ProbeEvent;
  return proto.slowmo.ProbeEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.slowmo.ProbeEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.slowmo.ProbeEvent}
 */
proto.slowmo.ProbeEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.slowmo.RunqStatusEvent;
      reader.readMessage(value,proto.slowmo.RunqStatusEvent.deserializeBinaryFromReader);
      msg.setRunqStatusEvent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.slowmo.ProbeEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.slowmo.ProbeEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.slowmo.ProbeEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.ProbeEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRunqStatusEvent();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.slowmo.RunqStatusEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional RunqStatusEvent runq_status_event = 1;
 * @return {?proto.slowmo.RunqStatusEvent}
 */
proto.slowmo.ProbeEvent.prototype.getRunqStatusEvent = function() {
  return /** @type{?proto.slowmo.RunqStatusEvent} */ (
    jspb.Message.getWrapperField(this, proto.slowmo.RunqStatusEvent, 1));
};


/**
 * @param {?proto.slowmo.RunqStatusEvent|undefined} value
 * @return {!proto.slowmo.ProbeEvent} returns this
*/
proto.slowmo.ProbeEvent.prototype.setRunqStatusEvent = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.slowmo.ProbeEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.slowmo.ProbeEvent} returns this
 */
proto.slowmo.ProbeEvent.prototype.clearRunqStatusEvent = function() {
  return this.setRunqStatusEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.slowmo.ProbeEvent.prototype.hasRunqStatusEvent = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.slowmo.RunqStatusEvent.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.slowmo.RunqStatusEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.slowmo.RunqStatusEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.slowmo.RunqStatusEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.RunqStatusEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    procId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    currentPc: (f = msg.getCurrentPc()) && proto.slowmo.InterpretedPC.toObject(includeInstance, f),
    runqEntriesList: jspb.Message.toObjectList(msg.getRunqEntriesList(),
    proto.slowmo.RunqEntry.toObject, includeInstance),
    runnext: (f = msg.getRunnext()) && proto.slowmo.RunqEntry.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.slowmo.RunqStatusEvent}
 */
proto.slowmo.RunqStatusEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.slowmo.RunqStatusEvent;
  return proto.slowmo.RunqStatusEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.slowmo.RunqStatusEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.slowmo.RunqStatusEvent}
 */
proto.slowmo.RunqStatusEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProcId(value);
      break;
    case 2:
      var value = new proto.slowmo.InterpretedPC;
      reader.readMessage(value,proto.slowmo.InterpretedPC.deserializeBinaryFromReader);
      msg.setCurrentPc(value);
      break;
    case 3:
      var value = new proto.slowmo.RunqEntry;
      reader.readMessage(value,proto.slowmo.RunqEntry.deserializeBinaryFromReader);
      msg.addRunqEntries(value);
      break;
    case 4:
      var value = new proto.slowmo.RunqEntry;
      reader.readMessage(value,proto.slowmo.RunqEntry.deserializeBinaryFromReader);
      msg.setRunnext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.slowmo.RunqStatusEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.slowmo.RunqStatusEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.slowmo.RunqStatusEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.RunqStatusEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProcId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getCurrentPc();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.slowmo.InterpretedPC.serializeBinaryToWriter
    );
  }
  f = message.getRunqEntriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.slowmo.RunqEntry.serializeBinaryToWriter
    );
  }
  f = message.getRunnext();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.slowmo.RunqEntry.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 proc_id = 1;
 * @return {number}
 */
proto.slowmo.RunqStatusEvent.prototype.getProcId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.slowmo.RunqStatusEvent} returns this
 */
proto.slowmo.RunqStatusEvent.prototype.setProcId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional InterpretedPC current_pc = 2;
 * @return {?proto.slowmo.InterpretedPC}
 */
proto.slowmo.RunqStatusEvent.prototype.getCurrentPc = function() {
  return /** @type{?proto.slowmo.InterpretedPC} */ (
    jspb.Message.getWrapperField(this, proto.slowmo.InterpretedPC, 2));
};


/**
 * @param {?proto.slowmo.InterpretedPC|undefined} value
 * @return {!proto.slowmo.RunqStatusEvent} returns this
*/
proto.slowmo.RunqStatusEvent.prototype.setCurrentPc = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.slowmo.RunqStatusEvent} returns this
 */
proto.slowmo.RunqStatusEvent.prototype.clearCurrentPc = function() {
  return this.setCurrentPc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.slowmo.RunqStatusEvent.prototype.hasCurrentPc = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated RunqEntry runq_entries = 3;
 * @return {!Array<!proto.slowmo.RunqEntry>}
 */
proto.slowmo.RunqStatusEvent.prototype.getRunqEntriesList = function() {
  return /** @type{!Array<!proto.slowmo.RunqEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.slowmo.RunqEntry, 3));
};


/**
 * @param {!Array<!proto.slowmo.RunqEntry>} value
 * @return {!proto.slowmo.RunqStatusEvent} returns this
*/
proto.slowmo.RunqStatusEvent.prototype.setRunqEntriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.slowmo.RunqEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.slowmo.RunqEntry}
 */
proto.slowmo.RunqStatusEvent.prototype.addRunqEntries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.slowmo.RunqEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.slowmo.RunqStatusEvent} returns this
 */
proto.slowmo.RunqStatusEvent.prototype.clearRunqEntriesList = function() {
  return this.setRunqEntriesList([]);
};


/**
 * optional RunqEntry runnext = 4;
 * @return {?proto.slowmo.RunqEntry}
 */
proto.slowmo.RunqStatusEvent.prototype.getRunnext = function() {
  return /** @type{?proto.slowmo.RunqEntry} */ (
    jspb.Message.getWrapperField(this, proto.slowmo.RunqEntry, 4));
};


/**
 * @param {?proto.slowmo.RunqEntry|undefined} value
 * @return {!proto.slowmo.RunqStatusEvent} returns this
*/
proto.slowmo.RunqStatusEvent.prototype.setRunnext = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.slowmo.RunqStatusEvent} returns this
 */
proto.slowmo.RunqStatusEvent.prototype.clearRunnext = function() {
  return this.setRunnext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.slowmo.RunqStatusEvent.prototype.hasRunnext = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.slowmo.InterpretedPC.prototype.toObject = function(opt_includeInstance) {
  return proto.slowmo.InterpretedPC.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.slowmo.InterpretedPC} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.InterpretedPC.toObject = function(includeInstance, msg) {
  var f, obj = {
    file: jspb.Message.getFieldWithDefault(msg, 1, ""),
    line: jspb.Message.getFieldWithDefault(msg, 2, 0),
    func: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.slowmo.InterpretedPC}
 */
proto.slowmo.InterpretedPC.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.slowmo.InterpretedPC;
  return proto.slowmo.InterpretedPC.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.slowmo.InterpretedPC} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.slowmo.InterpretedPC}
 */
proto.slowmo.InterpretedPC.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFile(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLine(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFunc(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.slowmo.InterpretedPC.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.slowmo.InterpretedPC.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.slowmo.InterpretedPC} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.InterpretedPC.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFile();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLine();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getFunc();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string file = 1;
 * @return {string}
 */
proto.slowmo.InterpretedPC.prototype.getFile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.slowmo.InterpretedPC} returns this
 */
proto.slowmo.InterpretedPC.prototype.setFile = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 line = 2;
 * @return {number}
 */
proto.slowmo.InterpretedPC.prototype.getLine = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.slowmo.InterpretedPC} returns this
 */
proto.slowmo.InterpretedPC.prototype.setLine = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string func = 3;
 * @return {string}
 */
proto.slowmo.InterpretedPC.prototype.getFunc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.slowmo.InterpretedPC} returns this
 */
proto.slowmo.InterpretedPC.prototype.setFunc = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.slowmo.RunqEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.slowmo.RunqEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.slowmo.RunqEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.RunqEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    goId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    executionContext: (f = msg.getExecutionContext()) && proto.slowmo.InterpretedPC.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.slowmo.RunqEntry}
 */
proto.slowmo.RunqEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.slowmo.RunqEntry;
  return proto.slowmo.RunqEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.slowmo.RunqEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.slowmo.RunqEntry}
 */
proto.slowmo.RunqEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setGoId(value);
      break;
    case 2:
      var value = new proto.slowmo.InterpretedPC;
      reader.readMessage(value,proto.slowmo.InterpretedPC.deserializeBinaryFromReader);
      msg.setExecutionContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.slowmo.RunqEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.slowmo.RunqEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.slowmo.RunqEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.slowmo.RunqEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGoId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getExecutionContext();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.slowmo.InterpretedPC.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 go_id = 1;
 * @return {number}
 */
proto.slowmo.RunqEntry.prototype.getGoId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.slowmo.RunqEntry} returns this
 */
proto.slowmo.RunqEntry.prototype.setGoId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional InterpretedPC execution_context = 2;
 * @return {?proto.slowmo.InterpretedPC}
 */
proto.slowmo.RunqEntry.prototype.getExecutionContext = function() {
  return /** @type{?proto.slowmo.InterpretedPC} */ (
    jspb.Message.getWrapperField(this, proto.slowmo.InterpretedPC, 2));
};


/**
 * @param {?proto.slowmo.InterpretedPC|undefined} value
 * @return {!proto.slowmo.RunqEntry} returns this
*/
proto.slowmo.RunqEntry.prototype.setExecutionContext = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.slowmo.RunqEntry} returns this
 */
proto.slowmo.RunqEntry.prototype.clearExecutionContext = function() {
  return this.setExecutionContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.slowmo.RunqEntry.prototype.hasExecutionContext = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.slowmo);
