// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: slowmo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompileAndRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // Go source code from user.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileAndRunRequest) Reset() {
	*x = CompileAndRunRequest{}
	mi := &file_slowmo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileAndRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileAndRunRequest) ProtoMessage() {}

func (x *CompileAndRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileAndRunRequest.ProtoReflect.Descriptor instead.
func (*CompileAndRunRequest) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{0}
}

func (x *CompileAndRunRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CompileAndRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CompileAndRunOneof:
	//
	//	*CompileAndRunResponse_CompileError
	//	*CompileAndRunResponse_RuntimeError
	//	*CompileAndRunResponse_RunEvent
	CompileAndRunOneof isCompileAndRunResponse_CompileAndRunOneof `protobuf_oneof:"compile_and_run_oneof"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompileAndRunResponse) Reset() {
	*x = CompileAndRunResponse{}
	mi := &file_slowmo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileAndRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileAndRunResponse) ProtoMessage() {}

func (x *CompileAndRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileAndRunResponse.ProtoReflect.Descriptor instead.
func (*CompileAndRunResponse) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{1}
}

func (x *CompileAndRunResponse) GetCompileAndRunOneof() isCompileAndRunResponse_CompileAndRunOneof {
	if x != nil {
		return x.CompileAndRunOneof
	}
	return nil
}

func (x *CompileAndRunResponse) GetCompileError() *CompilationError {
	if x != nil {
		if x, ok := x.CompileAndRunOneof.(*CompileAndRunResponse_CompileError); ok {
			return x.CompileError
		}
	}
	return nil
}

func (x *CompileAndRunResponse) GetRuntimeError() *RuntimeError {
	if x != nil {
		if x, ok := x.CompileAndRunOneof.(*CompileAndRunResponse_RuntimeError); ok {
			return x.RuntimeError
		}
	}
	return nil
}

func (x *CompileAndRunResponse) GetRunEvent() *ProbeEvent {
	if x != nil {
		if x, ok := x.CompileAndRunOneof.(*CompileAndRunResponse_RunEvent); ok {
			return x.RunEvent
		}
	}
	return nil
}

type isCompileAndRunResponse_CompileAndRunOneof interface {
	isCompileAndRunResponse_CompileAndRunOneof()
}

type CompileAndRunResponse_CompileError struct {
	CompileError *CompilationError `protobuf:"bytes,1,opt,name=compile_error,json=compileError,proto3,oneof"`
}

type CompileAndRunResponse_RuntimeError struct {
	RuntimeError *RuntimeError `protobuf:"bytes,2,opt,name=runtime_error,json=runtimeError,proto3,oneof"`
}

type CompileAndRunResponse_RunEvent struct {
	RunEvent *ProbeEvent `protobuf:"bytes,3,opt,name=run_event,json=runEvent,proto3,oneof"`
}

func (*CompileAndRunResponse_CompileError) isCompileAndRunResponse_CompileAndRunOneof() {}

func (*CompileAndRunResponse_RuntimeError) isCompileAndRunResponse_CompileAndRunOneof() {}

func (*CompileAndRunResponse_RunEvent) isCompileAndRunResponse_CompileAndRunOneof() {}

type CompilationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompilationError) Reset() {
	*x = CompilationError{}
	mi := &file_slowmo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompilationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilationError) ProtoMessage() {}

func (x *CompilationError) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilationError.ProtoReflect.Descriptor instead.
func (*CompilationError) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{2}
}

func (x *CompilationError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RuntimeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_slowmo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ProbeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ProbeEventOneof:
	//
	//	*ProbeEvent_RunqStatusEvent
	ProbeEventOneof isProbeEvent_ProbeEventOneof `protobuf_oneof:"probe_event_oneof"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProbeEvent) Reset() {
	*x = ProbeEvent{}
	mi := &file_slowmo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeEvent) ProtoMessage() {}

func (x *ProbeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeEvent.ProtoReflect.Descriptor instead.
func (*ProbeEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{4}
}

func (x *ProbeEvent) GetProbeEventOneof() isProbeEvent_ProbeEventOneof {
	if x != nil {
		return x.ProbeEventOneof
	}
	return nil
}

func (x *ProbeEvent) GetRunqStatusEvent() *RunqStatusEvent {
	if x != nil {
		if x, ok := x.ProbeEventOneof.(*ProbeEvent_RunqStatusEvent); ok {
			return x.RunqStatusEvent
		}
	}
	return nil
}

type isProbeEvent_ProbeEventOneof interface {
	isProbeEvent_ProbeEventOneof()
}

type ProbeEvent_RunqStatusEvent struct {
	RunqStatusEvent *RunqStatusEvent `protobuf:"bytes,1,opt,name=runq_status_event,json=runqStatusEvent,proto3,oneof"`
}

func (*ProbeEvent_RunqStatusEvent) isProbeEvent_ProbeEventOneof() {}

type RunqStatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcId        int64                  `protobuf:"varint,1,opt,name=proc_id,json=procId,proto3" json:"proc_id,omitempty"`
	CurrentPc     *InterpretedPC         `protobuf:"bytes,2,opt,name=current_pc,json=currentPc,proto3" json:"current_pc,omitempty"`
	RunqEntries   []*RunqEntry           `protobuf:"bytes,3,rep,name=runq_entries,json=runqEntries,proto3" json:"runq_entries,omitempty"`
	Runnext       *RunqEntry             `protobuf:"bytes,4,opt,name=runnext,proto3" json:"runnext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunqStatusEvent) Reset() {
	*x = RunqStatusEvent{}
	mi := &file_slowmo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunqStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunqStatusEvent) ProtoMessage() {}

func (x *RunqStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunqStatusEvent.ProtoReflect.Descriptor instead.
func (*RunqStatusEvent) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{5}
}

func (x *RunqStatusEvent) GetProcId() int64 {
	if x != nil {
		return x.ProcId
	}
	return 0
}

func (x *RunqStatusEvent) GetCurrentPc() *InterpretedPC {
	if x != nil {
		return x.CurrentPc
	}
	return nil
}

func (x *RunqStatusEvent) GetRunqEntries() []*RunqEntry {
	if x != nil {
		return x.RunqEntries
	}
	return nil
}

func (x *RunqStatusEvent) GetRunnext() *RunqEntry {
	if x != nil {
		return x.Runnext
	}
	return nil
}

type InterpretedPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Func          string                 `protobuf:"bytes,3,opt,name=func,proto3" json:"func,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterpretedPC) Reset() {
	*x = InterpretedPC{}
	mi := &file_slowmo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterpretedPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterpretedPC) ProtoMessage() {}

func (x *InterpretedPC) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterpretedPC.ProtoReflect.Descriptor instead.
func (*InterpretedPC) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{6}
}

func (x *InterpretedPC) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *InterpretedPC) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *InterpretedPC) GetFunc() string {
	if x != nil {
		return x.Func
	}
	return ""
}

type RunqEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GoId             int64                  `protobuf:"varint,1,opt,name=go_id,json=goId,proto3" json:"go_id,omitempty"`
	ExecutionContext *InterpretedPC         `protobuf:"bytes,2,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunqEntry) Reset() {
	*x = RunqEntry{}
	mi := &file_slowmo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunqEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunqEntry) ProtoMessage() {}

func (x *RunqEntry) ProtoReflect() protoreflect.Message {
	mi := &file_slowmo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunqEntry.ProtoReflect.Descriptor instead.
func (*RunqEntry) Descriptor() ([]byte, []int) {
	return file_slowmo_proto_rawDescGZIP(), []int{7}
}

func (x *RunqEntry) GetGoId() int64 {
	if x != nil {
		return x.GoId
	}
	return 0
}

func (x *RunqEntry) GetExecutionContext() *InterpretedPC {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

var File_slowmo_proto protoreflect.FileDescriptor

const file_slowmo_proto_rawDesc = "" +
	"\n" +
	"\fslowmo.proto\x12\x06slowmo\".\n" +
	"\x14CompileAndRunRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\"\xe1\x01\n" +
	"\x15CompileAndRunResponse\x12?\n" +
	"\rcompile_error\x18\x01 \x01(\v2\x18.slowmo.CompilationErrorH\x00R\fcompileError\x12;\n" +
	"\rruntime_error\x18\x02 \x01(\v2\x14.slowmo.RuntimeErrorH\x00R\fruntimeError\x121\n" +
	"\trun_event\x18\x03 \x01(\v2\x12.slowmo.ProbeEventH\x00R\brunEventB\x17\n" +
	"\x15compile_and_run_oneof\"7\n" +
	"\x10CompilationError\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\"3\n" +
	"\fRuntimeError\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\"h\n" +
	"\n" +
	"ProbeEvent\x12E\n" +
	"\x11runq_status_event\x18\x01 \x01(\v2\x17.slowmo.RunqStatusEventH\x00R\x0frunqStatusEventB\x13\n" +
	"\x11probe_event_oneof\"\xc3\x01\n" +
	"\x0fRunqStatusEvent\x12\x17\n" +
	"\aproc_id\x18\x01 \x01(\x03R\x06procId\x124\n" +
	"\n" +
	"current_pc\x18\x02 \x01(\v2\x15.slowmo.InterpretedPCR\tcurrentPc\x124\n" +
	"\frunq_entries\x18\x03 \x03(\v2\x11.slowmo.RunqEntryR\vrunqEntries\x12+\n" +
	"\arunnext\x18\x04 \x01(\v2\x11.slowmo.RunqEntryR\arunnext\"K\n" +
	"\rInterpretedPC\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x12\n" +
	"\x04func\x18\x03 \x01(\tR\x04func\"d\n" +
	"\tRunqEntry\x12\x13\n" +
	"\x05go_id\x18\x01 \x01(\x03R\x04goId\x12B\n" +
	"\x11execution_context\x18\x02 \x01(\v2\x15.slowmo.InterpretedPCR\x10executionContext2_\n" +
	"\rSlowmoService\x12N\n" +
	"\rCompileAndRun\x12\x1c.slowmo.CompileAndRunRequest\x1a\x1d.slowmo.CompileAndRunResponse0\x01B$Z\"github.com/kailun2047/slowmo/protob\x06proto3"

var (
	file_slowmo_proto_rawDescOnce sync.Once
	file_slowmo_proto_rawDescData []byte
)

func file_slowmo_proto_rawDescGZIP() []byte {
	file_slowmo_proto_rawDescOnce.Do(func() {
		file_slowmo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slowmo_proto_rawDesc), len(file_slowmo_proto_rawDesc)))
	})
	return file_slowmo_proto_rawDescData
}

var file_slowmo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_slowmo_proto_goTypes = []any{
	(*CompileAndRunRequest)(nil),  // 0: slowmo.CompileAndRunRequest
	(*CompileAndRunResponse)(nil), // 1: slowmo.CompileAndRunResponse
	(*CompilationError)(nil),      // 2: slowmo.CompilationError
	(*RuntimeError)(nil),          // 3: slowmo.RuntimeError
	(*ProbeEvent)(nil),            // 4: slowmo.ProbeEvent
	(*RunqStatusEvent)(nil),       // 5: slowmo.RunqStatusEvent
	(*InterpretedPC)(nil),         // 6: slowmo.InterpretedPC
	(*RunqEntry)(nil),             // 7: slowmo.RunqEntry
}
var file_slowmo_proto_depIdxs = []int32{
	2, // 0: slowmo.CompileAndRunResponse.compile_error:type_name -> slowmo.CompilationError
	3, // 1: slowmo.CompileAndRunResponse.runtime_error:type_name -> slowmo.RuntimeError
	4, // 2: slowmo.CompileAndRunResponse.run_event:type_name -> slowmo.ProbeEvent
	5, // 3: slowmo.ProbeEvent.runq_status_event:type_name -> slowmo.RunqStatusEvent
	6, // 4: slowmo.RunqStatusEvent.current_pc:type_name -> slowmo.InterpretedPC
	7, // 5: slowmo.RunqStatusEvent.runq_entries:type_name -> slowmo.RunqEntry
	7, // 6: slowmo.RunqStatusEvent.runnext:type_name -> slowmo.RunqEntry
	6, // 7: slowmo.RunqEntry.execution_context:type_name -> slowmo.InterpretedPC
	0, // 8: slowmo.SlowmoService.CompileAndRun:input_type -> slowmo.CompileAndRunRequest
	1, // 9: slowmo.SlowmoService.CompileAndRun:output_type -> slowmo.CompileAndRunResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_slowmo_proto_init() }
func file_slowmo_proto_init() {
	if File_slowmo_proto != nil {
		return
	}
	file_slowmo_proto_msgTypes[1].OneofWrappers = []any{
		(*CompileAndRunResponse_CompileError)(nil),
		(*CompileAndRunResponse_RuntimeError)(nil),
		(*CompileAndRunResponse_RunEvent)(nil),
	}
	file_slowmo_proto_msgTypes[4].OneofWrappers = []any{
		(*ProbeEvent_RunqStatusEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slowmo_proto_rawDesc), len(file_slowmo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slowmo_proto_goTypes,
		DependencyIndexes: file_slowmo_proto_depIdxs,
		MessageInfos:      file_slowmo_proto_msgTypes,
	}.Build()
	File_slowmo_proto = out.File
	file_slowmo_proto_goTypes = nil
	file_slowmo_proto_depIdxs = nil
}
